version: "3"

### Networks ###
networks:
  default: {}

### Services ###
services:
  # Reverse proxy service
  proxy:
    image: haproxy:alpine
    depends_on:
      - api
      - static
      - web
    networks:
      - default
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./example.com.pem:/etc/ssl/example.com.pem:ro

  # API service
  api:
    image: nginx:stable-alpine
    networks:
      - default
    restart: unless-stopped

  # Static files service
  static:
    image: nginx:stable-alpine
    networks:
      - default
    restart: unless-stopped

  # Web site service
  web:
    image: nginx:stable-alpine
    networks:
      - default
    restart: unless-stopped
